task_base:
  task_name: passive_biv
  model_name: fe_heart_sim_sage
  exp_name: default
  overwrite_exp_folder: True
task_data:
  task_data_name: passive_biv
  overwrite_data: False
  overwrite_stats: False
  chunk_file_size: 25
  train_split_ratio: 0.8
  sections: [0, 20, 100, 250, 500, 1000]
  nodes_per_sections: [20, 30, 30, 10, 10]
  train_down_sampling_node: 10000
  val_down_sampling_node: 10000