task_base:
  exp_name: default
#  overwrite_exp_folder: True
  gpu: False
task_data:
  task_data_name: lvData
  overwrite_data: False
  overwrite_stats: False
  edge_indices_generate_method: 4
  n_shape_coeff: 32  # Number of shape coefficients to input to the emulator
  sections: [0, 20, 50, 100, 250, 500]
  nodes_per_sections: [20, 30, 30, 10, 10]
#  down_sampling: 1.0  # only happens on train dataset